package controls

import (
	"time"

	"github.com/google/uuid"
)

// GetEntityRegistrySeeds returns all entity definitions for SmartSure
func GetEntityRegistrySeeds() []ControlEntityRegistry {
	return []ControlEntityRegistry{
		{
			ID:              uuid.New(),
			EntityName:      "User",
			TableName:       "users",
			DisplayName:     "User Account",
			Description:     "System user accounts including customers and staff",
			PrimaryKeyField: "id",
			SensitiveFields: []string{"email", "phone", "ssn", "date_of_birth", "bank_account", "credit_card"},
			RelatedEntities: map[string]string{
				"Device":   "one_to_many",
				"Policy":   "one_to_many",
				"Claim":    "one_to_many",
				"Payment":  "one_to_many",
				"Document": "one_to_many",
			},
			IsActive:  true,
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:              uuid.New(),
			EntityName:      "Device",
			TableName:       "devices",
			DisplayName:     "Insured Device",
			Description:     "Devices covered by insurance policies",
			PrimaryKeyField: "id",
			SensitiveFields: []string{"imei", "serial_number", "mac_address"},
			RelatedEntities: map[string]string{
				"User":     "many_to_one",
				"Policy":   "one_to_many",
				"Claim":    "one_to_many",
				"Repair":   "one_to_many",
				"Document": "one_to_many",
			},
			IsActive:  true,
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:              uuid.New(),
			EntityName:      "Policy",
			TableName:       "policies",
			DisplayName:     "Insurance Policy",
			Description:     "Insurance policies covering devices",
			PrimaryKeyField: "id",
			SensitiveFields: []string{},
			RelatedEntities: map[string]string{
				"User":     "many_to_one",
				"Device":   "many_to_one",
				"Claim":    "one_to_many",
				"Payment":  "one_to_many",
				"Document": "one_to_many",
			},
			IsActive:  true,
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:              uuid.New(),
			EntityName:      "Claim",
			TableName:       "claims",
			DisplayName:     "Insurance Claim",
			Description:     "Claims filed against insurance policies with comprehensive workflow, investigation, fraud detection, and settlement features",
			PrimaryKeyField: "id",
			SensitiveFields: []string{
				"bank_account_for_payout",
				"witness_contact",
				"police_report_number",
				"payment_reference",
				"bank_account_details",
			},
			RelatedEntities: map[string]string{
				"User":                     "many_to_one",
				"Device":                   "many_to_one",
				"Policy":                   "many_to_one",
				"Payment":                  "one_to_many",
				"Repair":                   "one_to_one",
				"ClaimInvestigationDetail": "one_to_one",
				"ClaimFraudDetection":      "one_to_one",
				"ClaimWorkflow":            "one_to_one",
				"ClaimSettlementDetail":    "one_to_one",
				"ClaimPayment":             "one_to_many",
				"ClaimReserve":             "one_to_one",
				"ClaimSubrogation":         "one_to_one",
				"ClaimAppeal":              "one_to_one",
				"ClaimCommunication":       "one_to_one",
				"ClaimAnalytics":           "one_to_one",
				"ClaimLitigation":          "one_to_one",
				"ClaimArbitration":         "one_to_one",
				"ClaimReporting":           "one_to_one",
				"Document":                 "one_to_many",
			},
			IsActive:  true,
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:              uuid.New(),
			EntityName:      "Payment",
			TableName:       "payments",
			DisplayName:     "Payment Transaction",
			Description:     "Payment transactions for premiums and claims",
			PrimaryKeyField: "id",
			SensitiveFields: []string{"card_number", "cvv", "account_number", "routing_number"},
			RelatedEntities: map[string]string{
				"User":     "many_to_one",
				"Policy":   "many_to_one",
				"Claim":    "many_to_one",
				"Document": "one_to_many",
			},
			IsActive:  true,
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:              uuid.New(),
			EntityName:      "Corporate",
			TableName:       "corporate_accounts",
			DisplayName:     "Corporate Account",
			Description:     "Business accounts with fleet management",
			PrimaryKeyField: "id",
			SensitiveFields: []string{"tax_id", "bank_details"},
			RelatedEntities: map[string]string{
				"User":   "one_to_many",
				"Device": "one_to_many",
				"Policy": "one_to_many",
			},
			IsActive:  true,
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:              uuid.New(),
			EntityName:      "Technician",
			TableName:       "technicians",
			DisplayName:     "Service Technician",
			Description:     "Authorized repair technicians",
			PrimaryKeyField: "id",
			SensitiveFields: []string{"license_number", "certification_number"},
			RelatedEntities: map[string]string{
				"Repair":         "one_to_many",
				"ServiceRequest": "one_to_many",
			},
			IsActive:  true,
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:              uuid.New(),
			EntityName:      "Vendor",
			TableName:       "vendors",
			DisplayName:     "Service Vendor",
			Description:     "Third-party service providers",
			PrimaryKeyField: "id",
			SensitiveFields: []string{"tax_id", "bank_account"},
			RelatedEntities: map[string]string{
				"Technician":     "one_to_many",
				"ServiceRequest": "one_to_many",
			},
			IsActive:  true,
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:              uuid.New(),
			EntityName:      "Repair",
			TableName:       "repairs",
			DisplayName:     "Device Repair",
			Description:     "Device repair records",
			PrimaryKeyField: "id",
			SensitiveFields: []string{},
			RelatedEntities: map[string]string{
				"Device":     "many_to_one",
				"Claim":      "one_to_one",
				"Technician": "many_to_one",
			},
			IsActive:  true,
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:              uuid.New(),
			EntityName:      "ServiceRequest",
			TableName:       "service_requests",
			DisplayName:     "Service Request",
			Description:     "Customer service requests",
			PrimaryKeyField: "id",
			SensitiveFields: []string{},
			RelatedEntities: map[string]string{
				"User":       "many_to_one",
				"Device":     "many_to_one",
				"Technician": "many_to_one",
				"Vendor":     "many_to_one",
			},
			IsActive:  true,
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:              uuid.New(),
			EntityName:      "Document",
			TableName:       "documents",
			DisplayName:     "Document",
			Description:     "Documents with comprehensive management, versioning, signatures, workflows, and compliance features",
			PrimaryKeyField: "id",
			SensitiveFields: []string{
				"con_hash",
				"md_author_email",
				"md_copyright",
				"comp_pii_detected",
				"comp_phi_detected",
				"proc_signature_data",
			},
			RelatedEntities: map[string]string{
				"User":                   "many_to_one",
				"Policy":                 "many_to_one",
				"Claim":                  "many_to_one",
				"Payment":                "many_to_one",
				"Device":                 "many_to_one",
				"DocumentOCR":            "one_to_one",
				"DocumentWorkflow":       "one_to_one",
				"DocumentVersion":        "one_to_many",
				"DocumentShare":          "one_to_many",
				"DocumentAuditLog":       "one_to_many",
				"DocumentRetention":      "one_to_one",
				"DocumentAnalytics":      "one_to_one",
				"DocumentCompliance":     "one_to_one",
				"DocumentClassification": "one_to_one",
				"DocumentIntegration":    "one_to_many",
			},
			IsActive:  true,
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
	}
}
